### ISSUE TITLE
Implement OS notifications for macOS.

### ISSUE THREAD

**Issue by TheVeryStarlk** [StarlkYT/Athan#2]
https://github.com/pr8x/DesktopNotifications#help-wanted

**Comment by Zekiah-A** [comment]
I think this whole desktop notif lib is bad, and probably outdated as even getting it to build a project with the lib is hard, maybe this library should be ditched completely, and instead just OS specific system library calls can be used, such as whatever windows uses with win32, libnotify/dbus on linux, and NSNotifications on OSX. https://developer.apple.com/documentation/foundation/nsusernotification (this is the old, simpler lib, but it seems deprecated) https://developer.apple.com/documentation/usernotifications/scheduling_a_notification_locally_from_your_app?language=objc (this is the newer method, but I am not sure how you would recreate these Objective-C classes in C#)

**Comment by Zekiah-A** [comment]
https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications?language=objc This would be so easy if apple did not use objective L, or whatever stupid language they use nowadays, as I don't think you can import methods from non-C/C++ libraries into a C# program, and definitely not the classes that they are using here (why couldn't apple just make these libraries static and functional lol).
